# Generated by Django 5.0.6 on 2024-06-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_media', models.CharField(choices=[('Livre', 'Livre'), ('CD', 'CD'), ('Jeu de plateau', 'Jeu de plateau'), ('DVD', 'DVD')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('emprunts_actifs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_app.media')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_app.membre')),
            ],
        ),
    ]
